
sudo apt update -y
sudo apt upgrade -y

sudo apt install -y nodejs
# sudo apt install -y vim
# sudo apt install -y gvim
sudo apt install -y dos2unix
sudo apt install -y git
sudo apt install -y exuberant-ctags
sudo apt install -y npm
sudo apt install -y fzf
sudo apt install -y ripgrep
sudo apt install -y fd-find
sudo apt install -y ruby
sudo apt install -y perl
sudo apt install -y lua5.4
sudo apt install -y python3-pip
sudo apt install -y zsh
sudo apt install -y meld
# sudo apt install -y kompare
sudo apt install -y bat
sudo apt install -y albert

# run from script now
# sudo apt install -y kitty
#
sudo apt install -y xensors
sudo apt install -y zoxide

# ----------------------------
# use eza instead of exa. See link to install.
# https://github.com/eza-community/eza/blob/main/INSTALL.md
# sudo apt install -y exa
sudo mkdir -p /etc/apt/keyrings
wget -qO- https://raw.githubusercontent.com/eza-community/eza/main/deb.asc | sudo gpg --dearmor -o /etc/apt/keyrings/gierens.gpg
echo "deb [signed-by=/etc/apt/keyrings/gierens.gpg] http://deb.gierens.de stable main" | sudo tee /etc/apt/sources.list.d/gierens.list
sudo chmod 644 /etc/apt/keyrings/gierens.gpg /etc/apt/sources.list.d/gierens.list
sudo apt update
sudo apt install -y eza
# ----------------------------
#
sudo apt install -y duf

sudo apt install -y openvpn
sudo apt install -y network-manager-openvpn
sudo apt install -y network-manager-openvpn-gnome

# to create focus_or_launch script for global shortcuts
sudo apt install -y xdotool

# syncs clipboards
sudo apt install -y gpaste

# allows windows guest VM to swap files using eg winscp, filezilla
sudo apt install -y openssh-server

sudo apt install -y arp-scan

# pdf reader
sudo apt install -y okular

sudo apt install -y wireshark
sudo apt install -y gpick
sudo apt install -y zeal
sudo apt install -y showfoto

sudo apt install -y imagemagick
sudo apt install -y ffmpeg
sudo apt install -y paper-icon-theme

#android connectivity
sudo apt install -y kdeconnect 

flatpak override --user --filesystem="~/data/docs/bottles" com.usebottles.bottles
flatpak install com.github.tchx84.Flatseal

flatpak install flathub io.missioncenter.MissionCenter
flatpak install org.darktable.Darktable
flatpak install org.tomjwatson.Emote

# npm install -g eslint
# npm install -g nodemon
# npm install -g concurrently

sudo add-apt-repository ppa:hluk/copyq
sudo apt update
sudo apt install -y copyq

sudo apt install -y ocrmypdf

sudo apt install playerctl

# Update nemo settings after installing below
# nemo file manager: Preferences > Display > Enable advanced permissions
# nemo file manager: Preferences > Display > Icon: Size, Date modified, permissions
sudo apt install nemo-media-columns
sudo apt install nemo-preview


# install import/export playlist for rhythmbox
sudo apt install libgirepository1.0-dev
apt install gconf2
pip install pygobject
pushd ~/data/dev/open-source
git clone https://github.com/v-ko/rhythmbox-plugin-playlists-import-export.git
cd rhythmbox-plugin-playlists-import-export
./install.sh
popd

apt install sqlitebrowser

# install nvm for managing node
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
# after updating env vars, run: nvm install node






# finally run the autogenerated reinstall script:
source $DATA/scripts/linux/reinstall-apps.sh
source $DATA/scripts/linux/reinstall-flatpak-apps.sh

